// Generated by CoffeeScript 1.3.3
(function() {
  var App, CoffeeScript, cp;

  cp = require('child_process');

  CoffeeScript = require("coffee-script");

  App = {};

  App.notify = function(title, message, type) {
    var args, timeout;
    args = [];
    timeout = type === "success" ? 1000 : 4000;
    args.push('-t', timeout);
    args.push('-i', "" + __dirname + "/i/coffee-" + type + ".png");
    args.push("" + title, "" + message);
    console.log('notify-send', args.join(' '));
    return cp.spawn('notify-send', args);
  };

  CoffeeScript.on('failure', function(error, task) {
    return App.notify('Coffee-Script faild:', "" + error, "error");
  });

  CoffeeScript.on('success', function(task) {
    return App.notify('Coffee-Script compiled:', "" + task.file + " sucessfully compiled!", "success");
  });

}).call(this);
